project:
  type: website
  output-dir: docs
  
  
website:
  title: "Arkadi Avanesyan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Courses.qmd
        text: Courses
      - href: CorporateTrainings.qmd
        text: Corporate Training

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

